HappyDogShop2/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HappyDogShop2.Models
{
    public class Product
    {
        public int ProductId { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane"), Display(Name = "Nazwa")]
        public string Name { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane"), StringLength(60, MinimumLength = 3), Display(Name = "Opis")]
        public string Description { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane"), Range(1, 10000), Display(Name = "Cena")] //mozna zrobic wlasny validator
        public float Price { get; set; }
        [DefaultValue(false), Display(Name = "Ukryty")]
        public bool IsHidden { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane"), Display(Name = "Stan magazynowy")]
        public int StockCount { get; set; }
        
        
        [Required(ErrorMessage = "To pole jest wymagane"), Display(Name = "Obraz ")]
        public int MediaTypeId { get; set; }
        public virtual MediaType MediaType { get; set; }
        
        [ForeignKey("Category"), Display(Name = "Kategoria")]
        public int CategoryId { get; set; }
        public virtual Category Category { get; set; }
        
        [ForeignKey("Sale"), Display(Name = "Promocja")]
        public int? SaleId { get; set; }
        public virtual Sale Sale { get; set; }
    }
}

HappyDogShop2/Controllers/CartItemController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using HappyDogShop2.Models;

namespace HappyDogShop2.Controllers
{
    public class CartItemController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: CartItems
        public ActionResult Index(int OrderId = -1)
        {
            List<CartItem> list= new List<CartItem>();
            if (OrderId != -1)
            {
                list = db.CartItems.Where(cartItem => cartItem.OrderId == OrderId).ToList();
            }
            else
            {
                list = db.CartItems.ToList();
            }
            return View(list);
        }

        // GET: CartItems/Details/5
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // GET: CartItems/Create
        public ActionResult Create()
        {
            prepareList();
            return View();
        }

        // POST: CartItems/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemId,Quantity,ProductId, OrderId")] CartItem cartItem)
        {
            //TODO jak zrobic to zeby przy braku otwartego zamowienia tworzylo nowe
            // if (cartItem.OrderId = null)
            // {
            //     Order order = new Order();
            //     Session["orderId"] = order.OrderId;
            // }
            if (ModelState.IsValid)
            {
                db.CartItems.Add(cartItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cartItem);
        }
        public ActionResult Create2(int Quantity, int ProductId, int? OrderId)
        {
            Console.Write(OrderId);
            if (OrderId == null)
            {
                if (Session["userId"] == null)
                {
                    return RedirectToAction("Index", "Login");
                }
                else
                {
                    Order order = new Order();
                    order.UserId = (int) Session["userId"];
                    order.Date = DateTime.Now;
                    db.Orders.Add(order);
                    db.SaveChanges();                    
                    Session["orderId"] = order.OrderId;
                }
            }

            CartItem cartItem = new CartItem();
            cartItem.Quantity = Quantity;
            cartItem.ProductId = ProductId;
            cartItem.OrderId = (int) Session["orderId"];
            db.CartItems.Add(cartItem);
            db.SaveChanges();
            return RedirectToAction("UserIndex", new { OrderId=cartItem.OrderId} );

        }

        // GET: CartItems/Edit/5
        public ActionResult Edit(int? id)
        {
            prepareList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemId,Quantity,ProductId, OrderId")] CartItem cartItem)
        {
            db.Entry(cartItem).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("UserIndex");
            if (ModelState.IsValid)
            {
                db.Entry(cartItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("UserIndex");
            }
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartItem cartItem = db.CartItems.Find(id);
            db.CartItems.Remove(cartItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult UserIndex(int? OrderId = 0)
        {
            ViewData["categories"] = from category in db.Categories select category;
            ViewData["media"] = from media in db.MediaTypes select media;
            ViewData["products"] = from product in db.Products select product;
            ViewBag.orderId = OrderId;
            float sum = 0;
            
            List<CartItem> list= new List<CartItem>();
            
            if (OrderId > 0)
            {
                list = db.CartItems.Where(cartItem => cartItem.OrderId == OrderId).ToList();
            }
            foreach (CartItem item in list)
            {
                Product product = db.Products.Find(item.ProductId);
                sum += product.Price * item.Quantity;
            }

            ViewBag.sum = sum;
            return View(list);
        }
        public void prepareList()
        {
            List<SelectListItem> productList = new List<SelectListItem>();
            List<SelectListItem> orderList = new List<SelectListItem>();

            foreach (var product in db.Products) productList.Add(new SelectListItem{ Text = product.Name, Value = product.ProductId.ToString()});
            foreach (var order in db.Orders) orderList.Add(new SelectListItem{ Text = order.OrderId.ToString(), Value = order.OrderId.ToString()});

            ViewData["productList"] = productList;
            ViewData["orderList"] = orderList;
        }
    }
}

HappyDogShop2/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using HappyDogShop2.Models;

namespace HappyDogShop2.Controllers
{
    public class UserController : Controller
    {
        private MyDbContext db = new MyDbContext();
        
        // GET Users
        public ActionResult Index(bool AllUsers=true, bool IsAdmin=false, string FirstName = "", string LastName = "", string City = "",
            string Country = "")
        {
            List<User> list = db.Users.ToList();
            
            if (AllUsers != true) list = list.Where(user => user.IsAdmin == IsAdmin).ToList();
            
            if (FirstName != "") list = list.Where(user => user.FirstName == FirstName).ToList();

            if (LastName != "") list = list.Where(user => user.LastName == LastName).ToList();
            
            if (City != "") list = list.Where(user => user.City == City).ToList();
            
            if (Country != "") list = list.Where(user => user.Country == Country).ToList();
            
            return View(list);        
        }
    
    
    // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        
        // GET: Users/Create
        public ActionResult Create()
        {
            prepareList();
            return View();
        }
        
        // POST: Users/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,FirstName,LastName,Username,Password,IsAdmin,PhoneNumber,Address,City,Country,ZipCode, SaleId")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
             prepareList();
            if (id == null)
            {
                prepareList();
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                prepareList();
                return HttpNotFound();
            }
            prepareList();
            return View(user);
        }

        // POST: Users/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,FirstName,LastName,Username,Password,IsAdmin,PhoneNumber,Address,City,Country,ZipCode, SaleId")] User user)
        {
            Console.Write("sale" + user.SaleId);
            if (ModelState.IsValid)
            {
                Console.Write("sale" + user.SaleId);
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            prepareList();

            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult EditPassword(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPassword([Bind(Include = "UserId,FirstName,LastName,Username,Password,IsAdmin,PhoneNumber,Address,City,Country,ZipCode, SaleId")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public void prepareList()
        {
            List<SelectListItem> saleUserList = new List<SelectListItem>();

            foreach (var sale in db.Sales) saleUserList.Add(new SelectListItem{ Text = sale.Name + ": " + sale.ValueInPercent + "%", Value = sale.SaleId.ToString()});

            ViewData["saleUserList"] = saleUserList;
        }
}}

HappyDogShop2/Views/Products/AdminDelete.cshtml
@model HappyDogShop2.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h4>Czy jesteś pewien, że chcesz usunąć ten produkt?</h4>
<div>
    <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsHidden)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsHidden)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StockCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StockCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MediaTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MediaTypeId)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryId)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.SaleId)
        </dt>
        
        <dd>
            @Html.DisplayFor(model => model.SaleId)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" style="margin-left: 215px; border-color: #e43e86" /> |
            @Html.ActionLink("Wróć", "AdminIndex")
        </div>
    }
</div>

HappyDogShop2/Views/Products/AdminDetails.cshtml
@model HappyDogShop2.Models.Product

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>Szczegóły:</h4>
    <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsHidden)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsHidden)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StockCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StockCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MediaTypeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MediaType.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.SaleId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sale.Name)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "AdminEdit", new { id = Model.ProductId}) |
    @Html.ActionLink("Wróć", "AdminIndex")
</p>

HappyDogShop2/Views/Products/AdminIndex.cshtml
@model IEnumerable<HappyDogShop2.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h4>Produkty:</h4>

<p>
    @Html.ActionLink("Utwórz nowy", "AdminCreate")
</p>

<form asp-controller="User" asp-action="Index" method="get">

    <p>
        Nazwa: <input type="text" name="Name"/>
    </p>
    
    <p>
        Przedział cenowy
    </p>

    <input style="width: 25%; outline: none; opacity: 0.7;
   height: 20px; background: #e43e86; cursor: grab; -webkit-appearance: none;
" id="minPrice" type="range" name="Price1" min=@ViewBag.min max=@ViewBag.max value=@ViewBag.min  onchange="func()"/>
    <p id="min"></p>
    <input style="width: 25%; outline: none; opacity: 0.7;
   height: 20px; background: #e43e86; cursor: grab; -webkit-appearance: none; " id="maxPrice" type="range" name="Price2" min=@ViewBag.min max=@ViewBag.max value=@ViewBag.max onchange="func()"/>
    <p id="max"></p>
    <script>
        func()        
        function func (){
            let min = document.getElementById('minPrice');
            let max = document.getElementById('maxPrice'); 
            document.getElementById('min').innerHTML = min.value
            document.getElementById('max').innerHTML = max.value
        }
    </script>
    
    <p>
        Kategoria: <input type="text" name="CategoryName"/>
    </p>
    
    <p>
        Promocje: <input type="hidden" name="Sale" value="false"><input type="checkbox" onclick="this.previousSibling.value=true">
    </p>
    
    <p>
        Na stanie: <input type="hidden" name="InStock" value="true"><input type="checkbox" checked="checked" onclick="this.previousSibling.value=false">
    </p>
    
    <p>
        <input type="submit" value="Szukaj"/>
    </p>
    
    
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProductId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsHidden)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StockCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MediaTypeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SaleId)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ProductId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsHidden)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StockCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MediaType.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sale.Name)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "AdminEdit", new {id = item.ProductId}) |
            @Html.ActionLink("Szczegóły", "AdminDetails", new {id = item.ProductId}) |
            @Html.ActionLink("Usuń", "AdminDelete", new {id = item.ProductId})
        </td>
    </tr>
}

</table>

HappyDogShop2/Views/Products/Index.cshtml
@model IEnumerable<HappyDogShop2.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h4>Produkty:</h4>

<p>
    @Html.ActionLink("Utwórz nowy", "Create")
</p>

<form asp-controller="User" asp-action="Index" method="get">

    <p>
        Nazwa: <input type="text" name="Name"/>
    </p>
    
    <p>
        Przedział cenowy
    </p>

    <p>
        Kategoria: <input type="text" name="CategoryId"/>
    </p>
    
    <p>
        Promocje: <input type="hidden" name="Sale" value="false"><input type="checkbox" onclick="this.previousSibling.value=true">
    </p>
    
    <p>
        <input type="submit" value="Szukaj"/>
    </p>
    
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsHidden)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StockCount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleasedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MediaTypeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsHidden)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StockCount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleasedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MediaTypeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryId)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.ProductId }) |
            @Html.ActionLink("Szczegóły", "Details", new { id=item.ProductId }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.ProductId })
        </td>
    </tr>
}

</table>

HappyDogShop2/Views/Products/UserIndex.cshtml
@model PagedList.IPagedList<HappyDogShop2.Models.Product>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@using System.Collections
@using System.Collections.Specialized
@using HappyDogShop2.Models

@{
    ViewBag.Title = "UserIndex";
    Layout = "_ProductLayout.cshtml";
    ViewBag.NewProducts = Model.OrderByDescending(product => product.ProductId).Take(10).ToList();
    
}

<h4>Produkty:</h4>
@section sales {
    <div style="display: grid; grid-template-columns: 400px 350px 400px; grid-template-rows: 200px; column-gap: 10px; row-gap: 15px;
                 justify-items: center;  align-items: center; text-align: center;">
            <div>
                <img style="height: 150px" src="https://lillypetshop.pl/1076-big_default/organiczna-pilka-rainbow-green.jpg">
            </div>
            <div>
                <h3>@Html.ActionLink("Skorzystaj z naszych promocji", "Contact", "Home")</h3>
            </div>
            <div>
                <img style="height: 150px"  src="https://lillypetshop.pl/950-thickbox_default/royal-nap-legowisko-dla-sredniego-i-duzego-psa-silver-grey.jpg">
            </div>
        </div>
}

@section leftMenu
{
    @* <div style="width: 80%; margin: 50px auto ; background-color: #f7e6cf; padding: 20px"> *@

        <p  style="color: #e43e86" >@Html.ActionLink("wszystko", "UserIndex", new { categoryId = -1 })</p>

        <p>@Html.ActionLink("nowości", "UserIndex", new { categoryId = -2 })</p>

        <p>@Html.ActionLink("promocje", "UserIndex", new { categoryId = -3 })</p>
    
        @foreach (var c in (IEnumerable<Category>)ViewData["categories"])
        {
        if (c.Parent == null && c.IsHidden == false)
        {
            <p>@Html.ActionLink(@c.Name, "UserIndex", new { categoryId = c.CategoryId })</p>
           foreach (var item in (IEnumerable<Category>) ViewData["categories"])
           {
               if (c.CategoryId == item.ParentId && item.IsHidden == false)
               {
               <p style="margin-left: 20px">@Html.ActionLink(@item.Name, "UserIndex", new { categoryId = item.CategoryId })</p>
               foreach (var item2 in (IEnumerable<Category>) ViewData["categories"])
               {
                   if (item.CategoryId == item2.ParentId && item2.IsHidden == false)
                   {
                       <p  style="margin-left: 40px"> @Html.ActionLink(@item2.Name, "UserIndex", new { categoryId = item2.CategoryId })</p>
                       foreach (var item3 in (IEnumerable<Category>) ViewData["categories"])
                       {
                           if (item2.CategoryId == item3.ParentId && item3.IsHidden == false)
                           {
                               <p  style="margin-left: 60px">@Html.ActionLink(@item3.Name, "UserIndex", new { categoryId = item3.CategoryId })</p>
                           }
                       }
                   }
               }
               }
           }
        }
    }
        
    @* </div> *@
}
@section productList {

    
    <div style="width: 100%; margin: 0 auto auto; display: grid; grid-template-columns: 250px 250px 250px;
                                             grid-template-rows: 400px; 
                                             column-gap: 10px;
                                             row-gap: 15px; justify-items: center">
        @foreach (var item in Model)
        {
            if (item.IsHidden == false && item.Category.IsHidden == false )
            {
                <div style=" background: rgba(230,95,140,0.13);text-align: center; padding: 10px">
                    
                    @foreach (var media in (IEnumerable<MediaType>) ViewData["media"])
                    {
                        if (@item.MediaTypeId == media.MediaTypeId)
                        {
                            <img style="height: 150px" src="@media.ImagePath"/>
                        }
                    }
                    <h2>@Html.ActionLink(@item.Name, "UserDetails", new { id = item.ProductId})</h2>
                
                    <h5>
                        cena: @item.Price zł
                    </h5>
       
                    @* <input type="submit" value="Dodaj do koszyka" class="btn btn-default" style=" border-color: #e43e86" onclick=""/> *@
                    <button class="btn btn-default" style=" border-color: #e43e86">@Html.ActionLink("Dodaj do koszyka", "Create2", "CartItem", new { Quantity = 1, ProductId = item.ProductId, OrderID = @Session["orderId"]}, new {})</button>
                </div>
            }
        }  


    </div>
    <div style="display: block; align-items: center; justify-content: center">
        <div>
        </div>
        <div>
              </div>

    </div>
}

@section pageNumbers
{
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("UserIndex",
                              new {page}))
              
}
       