HappyDogShop2/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using HappyDogShop2.Models;

namespace HappyDogShop2.Controllers
{
    public class OrderController : Controller
    {
       private MyDbContext db = new MyDbContext();

        // GET: Orders
        public ActionResult Index(int UserId = -1)
        {
            List<Order> list= new List<Order>();
            if (UserId != -1)
            {
                list = db.Orders.Where(order => order.UserId == UserId).ToList();
            }
            else
            {
                list = db.Orders.ToList();
            }
            return View(list);
        }
        
        public ActionResult UserIndex(int UserId)
        {
            List<Order> list= new List<Order>();
            list = db.Orders.Where(order => order.UserId == UserId).ToList();
            foreach (var order in list)
            {
                ViewData[order.OrderId.ToString()] = order.CartItems;
            }

            ViewBag.count = 0;
            return View(list);
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            prepareList();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewData["cartItems"] = db.CartItems.Where(item => item.Order.OrderId == order.OrderId).ToList();
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
        
            return View();
        }

        // POST: Orders/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderId,UserId,AmountPaid, Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            Session["orderId"] = order.OrderId;
            return View(order);
        }
        
        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId,UserId,AmountPaid, Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                if (Status.Otwarte.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Otwarte;
                if (Status.Zapłacone.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Zapłacone;
                if (Status.Dostarczone.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Dostarczone;
                if (Status.Przyjęte.ToString().Equals(Request.Form["wybrany"]))  order.Status = Status.Przyjęte;
                if (Status.Wysłane.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Wysłane;
                
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult OrderAgain(int? NewOrderId, int OldOrderId)
        {
            if (NewOrderId == null)
            {
                Order order = new Order();
                Console.Write((int) Session["userId"]);
                    order.UserId = (int) Session["userId"];
                    order.Date = DateTime.Now;
                    db.Orders.Add(order);
                    db.SaveChanges();                    
                    Session["orderId"] = order.OrderId;
                
            }

            foreach (var item in db.CartItems.Where(i=>i.OrderId == OldOrderId))
            {
                CartItem cartItem = new CartItem();
                cartItem.Quantity = item.Quantity;
                cartItem.ProductId = item.ProductId;
                cartItem.OrderId = (int) Session["orderId"];
                db.CartItems.Add(cartItem);
            }
            
            db.SaveChanges();
            return RedirectToAction("UserIndex", "CartItem", new { OrderId=(int) Session["orderId"]} );
        }
        
        public ActionResult PlaceAnOrder(int OrderId, decimal AmountPaid)
        {
            Order order = db.Orders.Find(OrderId);
            Console.Write(order.UserId);
            order.AmountPaid = AmountPaid;
            order.Status = Status.Przyjęte;

            List<CartItem> itemList = new List<CartItem>();
            itemList = db.CartItems.Where(item => item.Order.OrderId == order.OrderId).ToList();
            foreach (var item in itemList) db.Products.Where(product => product.ProductId == item.ProductId).ToList().ForEach(pr => pr.StockCount = pr.StockCount - item.Quantity);
            
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("UserIndex", new {UserId = order.UserId});
        }
        public void prepareList()
        {
            ViewData["media"] = from media in db.MediaTypes select media;
            List<SelectListItem> productList = new List<SelectListItem>();
            List<SelectListItem> orderList = new List<SelectListItem>();
            List<SelectListItem> mediaList = new List<SelectListItem>();
            
            foreach (var product in db.Products) productList.Add(new SelectListItem{ Text = product.Name, Value = product.ProductId.ToString()});
            foreach (var order in db.Orders) orderList.Add(new SelectListItem{ Text = order.OrderId.ToString(), Value = order.OrderId.ToString()});
            foreach (var media in db.MediaTypes) mediaList.Add(new SelectListItem{ Text = media.Title, Value = media.MediaTypeId.ToString()});
            
            ViewData["productList"] = productList;
            ViewData["orderList"] = orderList;
            ViewData["mediaList"] = mediaList;
        }
    }
}

HappyDogShop2/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HappyDogShop2.Models;

namespace HappyDogShop2.Controllers
{
    public class SalesController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: Sales
        public ActionResult Index(string searchString = "")
        {
            List<Sale> list= new List<Sale>();
            if (searchString != "")
            {
                list = db.Sales.Where(sale => sale.Name == searchString).ToList();
            }
            else
            {
                list = db.Sales.ToList();
            }
            return View(list);
        }

        // GET: Sales/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // GET: Sales/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sales/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SaleId,StartDate,EndDate,Name,ValueInPercent")] Sale sale)
        {
            if (ModelState.IsValid)
            {
                db.Sales.Add(sale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sale);
        }

        // GET: Sales/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // POST: Sales/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SaleId,StartDate,EndDate,Name,ValueInPercent")] Sale sale)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sale);
        }

        // GET: Sales/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sale sale = db.Sales.Find(id);
            db.Sales.Remove(sale);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HappyDogShop2/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using HappyDogShop2.Models;

namespace HappyDogShop2.Controllers
{
    public class UserController : Controller
    {
        private MyDbContext db = new MyDbContext();
        
        // GET Users
        public ActionResult Index(bool AllUsers=true, bool IsAdmin=false, string FirstName = "", string LastName = "", string City = "",
            string Country = "")
        {
            List<User> list = db.Users.ToList();
            
            if (AllUsers != true) list = list.Where(user => user.IsAdmin == IsAdmin).ToList();
            
            if (FirstName != "") list = list.Where(user => user.FirstName == FirstName).ToList();

            if (LastName != "") list = list.Where(user => user.LastName == LastName).ToList();
            
            if (City != "") list = list.Where(user => user.City == City).ToList();
            
            if (Country != "") list = list.Where(user => user.Country == Country).ToList();
            
            return View(list);        
        }
    
    
    // GET: Users/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        
        // GET: Users/Create
        public ActionResult Create()
        {
            prepareList();
            return View();
        }
        
        // POST: Users/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserId,FirstName,LastName,Username,Password,IsAdmin,PhoneNumber,Address,City,Country,ZipCode, SaleId")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(int? id)
        {
             prepareList();
            if (id == null)
            {
                prepareList();
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                prepareList();
                return HttpNotFound();
            }
            prepareList();
            return View(user);
        }

        // POST: Users/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserId,FirstName,LastName,Username,Password,IsAdmin,PhoneNumber,Address,City,Country,ZipCode, SaleId")] User user)
        {
            Console.Write("sale" + user.SaleId);
            if (ModelState.IsValid)
            {
                Console.Write("sale" + user.SaleId);
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            prepareList();

            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult EditPassword(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPassword([Bind(Include = "UserId,FirstName,LastName,Username,Password,IsAdmin,PhoneNumber,Address,City,Country,ZipCode, SaleId")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        public void prepareList()
        {
            List<SelectListItem> saleUserList = new List<SelectListItem>();

            foreach (var sale in db.Sales) saleUserList.Add(new SelectListItem{ Text = sale.Name + ": " + sale.ValueInPercent + "%", Value = sale.SaleId.ToString()});

            ViewData["saleUserList"] = saleUserList;
        }
}}

HappyDogShop2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("HappyDog Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    
                    <li>@Html.ActionLink("O nas", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Rejestracja", "Create", "User")</li>
                    <li>@Html.ActionLink("Produkty", "UserIndex", "Products")</li>
                    <li style="display:none" id="cart">@Html.ActionLink("Koszyk", "UserIndex", "CartItem", new {OrderId = @Session["orderId"]}, new {})</li>
                    <li  class="nav-item dropdown show" >
                        <a  id="admin" style="display:none"  class="btn dropdown-toggle" href="#" data-toggle="dropdown">Admin</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item">@Html.ActionLink("Kategorie", "Index", "Categories")</a>
                            <a class="dropdown-item">@Html.ActionLink("Promocje", "Index", "Sales")</a>
                            <a class="dropdown-item">@Html.ActionLink("Produkty", "AdminIndex", "Products")</a>
                            <a class="dropdown-item">@Html.ActionLink("Użytkownicy", "Index", "User")</a>
                            <a class="dropdown-item">@Html.ActionLink("Pliki", "Index", "MediaTypes")</a>
                            <a class="dropdown-item">@Html.ActionLink("Zamówienia", "Index", "Order")</a>
                            <a class="dropdown-item">@Html.ActionLink("Przedmioty koszykowe", "Index", "CartItem")</a>
                        </div>
                    </li>       
                    <li style="display:block" id="login">@Html.ActionLink("Login", "Index", "Login")</li>
                    <li class="nav-item dropdown show" style="margin-right: 0">
                        <a id="user" style="margin-left: 300px; display:none; " class="navbar-brand btn dropdown-toggle" href="#" data-toggle="dropdown">@Session["userName"]</a>
                        <div class="dropdown-menu-right dropdown-menu" >
                            <a class="dropdown-item">@Html.ActionLink("Informacje", "Details", "User", new { id=@Session["UserId"] }, "" )</a>
                            <a class="dropdown-item">@Html.ActionLink("Edytuj profil", "Edit", "User", new { id=@Session["UserId"] }, "" )</a>
                            <a class="dropdown-item">@Html.ActionLink("Zmień hasło", "EditPassword", "User", new { id=@Session["UserId"] }, "" )</a>
                            <a class="dropdown-item">@Html.ActionLink("Twoje zamówienia", "UserIndex", "Order", new { UserId=@Session["UserId"] }, "" )</a>
                        </div>
                    </li>       
                    <li style="display:none" id="logout" class="pull-left">@Html.ActionLink("Wyloguj", "LogOut", "Login" )</li>   
                    <script type="text/javascript">
                        if (@Session["userId"] !== 0 )
                        {
                           document.getElementById('logout').style.display='block'
                           document.getElementById('login').style.display='none'
                           document.getElementById('user').style.display='block'
                           document.getElementById('cart').style.display='block'
                           let isAdmin = '@Session["isAdmin"]' 
                           if (isAdmin === 'True')
                           {
                               document.getElementById('admin').style.display='block'
                           }
                        }
                        else 
                        {
                           document.getElementById('cart').style.display='none'
                           document.getElementById('logout').style.display='none'
                           document.getElementById('login').style.display='block'
                           document.getElementById('admin').style.display='none'
                           document.getElementById('user').style.display='none'
                        }
                    </script>
                </ul>
            </div>
        </div>
    </div>
    
    <div class="container body-content">
        <img src=""/>
        <hr />
                @RenderBody()
        <footer style=" width: 100%;  margin: 50px auto; color: #e43e86; background-color: white;  ">
                <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
            <div style="display: grid; grid-template-columns: 400px 350px 400px; grid-template-rows: 150px; column-gap: 10px; row-gap: 15px;
             justify-items: center;  align-items: center; text-align: center;">
                <div>
                    <h2>HappyDog Shop</h2>
                </div>
                <div>
                    <h3>Skontaktuj się z nami</h3>
                    <address>
                        <strong>Email:</strong> <a href="mailto:Support@example.com">happydogshop2022@gmail.com</a><br/>
                    </address>
                    @Html.ActionLink("formularz kontaktowy", "Contact", "Home")
                </div>
                <div>
                    <address>
                        Szczęśliwych Piesków 8<br/>
                        Białystok, 15-123<br/>
                        <abbr title="Phone">Telefon:</abbr>
                        123-456-789
                    </address>
                </div>


            </div>
                <p>&copy; @DateTime.Now.Year - HappyDog Shop</p>
                    <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>