HappyDogShop2/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HappyDogShop2.Models
{
    public enum Status
    {
        Otwarte, Przyjęte, Zapłacone, Wysłane, Dostarczone
    }
    public class Order
    {
        [Key]
        public int OrderId { get; set; }
        
        [ForeignKey("User"), Required(ErrorMessage = "To pole jest wymagane")]
        public int UserId { get; set; }
        public User User { get; set; }
        
        [Required(ErrorMessage = "To pole jest wymagane"), Display(Name = "Suma"), DefaultValue(0)]
        public decimal AmountPaid { get; set; }

        [DefaultValue(0)]
        public Status Status { get; set; }
        [Required(ErrorMessage = "To pole jest wymagane"), DataType(DataType.DateTime), Display(Name = "Data zamówienia")]
        public DateTime Date { get; set; } = DateTime.Now;
        public ICollection<CartItem> CartItems { get; set; }
    }
}

HappyDogShop2/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using HappyDogShop2.Models;

namespace HappyDogShop2.Controllers
{
    public class OrderController : Controller
    {
       private MyDbContext db = new MyDbContext();

        // GET: Orders
        public ActionResult Index(int UserId = -1)
        {
            List<Order> list= new List<Order>();
            if (UserId != -1)
            {
                list = db.Orders.Where(order => order.UserId == UserId).ToList();
            }
            else
            {
                list = db.Orders.ToList();
            }
            return View(list);
        }
        
        public ActionResult UserIndex(int UserId)
        {
            List<Order> list= new List<Order>();
            list = db.Orders.Where(order => order.UserId == UserId).ToList();
            foreach (var order in list)
            {
                ViewData[order.OrderId.ToString()] = order.CartItems;
            }

            ViewBag.count = 0;
            return View(list);
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            prepareList();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewData["cartItems"] = db.CartItems.Where(item => item.Order.OrderId == order.OrderId).ToList();
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
        
            return View();
        }

        // POST: Orders/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderId,UserId,AmountPaid, Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            Session["orderId"] = order.OrderId;
            return View(order);
        }
        
        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId,UserId,AmountPaid, Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                if (Status.Otwarte.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Otwarte;
                if (Status.Zapłacone.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Zapłacone;
                if (Status.Dostarczone.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Dostarczone;
                if (Status.Przyjęte.ToString().Equals(Request.Form["wybrany"]))  order.Status = Status.Przyjęte;
                if (Status.Wysłane.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Wysłane;
                
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult OrderAgain(int? NewOrderId, int OldOrderId)
        {
            if (NewOrderId == null)
            {
                Order order = new Order();
                Console.Write((int) Session["userId"]);
                    order.UserId = (int) Session["userId"];
                    order.Date = DateTime.Now;
                    db.Orders.Add(order);
                    db.SaveChanges();                    
                    Session["orderId"] = order.OrderId;
                
            }

            foreach (var item in db.CartItems.Where(i=>i.OrderId == OldOrderId))
            {
                CartItem cartItem = new CartItem();
                cartItem.Quantity = item.Quantity;
                cartItem.ProductId = item.ProductId;
                cartItem.OrderId = (int) Session["orderId"];
                db.CartItems.Add(cartItem);
            }
            
            db.SaveChanges();
            return RedirectToAction("UserIndex", "CartItem", new { OrderId=(int) Session["orderId"]} );
        }
        
        public ActionResult PlaceAnOrder(int OrderId, decimal AmountPaid)
        {
            Order order = db.Orders.Find(OrderId);
            Console.Write(order.UserId);
            order.AmountPaid = AmountPaid;
            order.Status = Status.Przyjęte;

            List<CartItem> itemList = new List<CartItem>();
            itemList = db.CartItems.Where(item => item.Order.OrderId == order.OrderId).ToList();
            foreach (var item in itemList) db.Products.Where(product => product.ProductId == item.ProductId).ToList().ForEach(pr => pr.StockCount = pr.StockCount - item.Quantity);
            
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("UserIndex", new {UserId = order.UserId});
        }
        public void prepareList()
        {
            ViewData["media"] = from media in db.MediaTypes select media;
            List<SelectListItem> productList = new List<SelectListItem>();
            List<SelectListItem> orderList = new List<SelectListItem>();
            List<SelectListItem> mediaList = new List<SelectListItem>();
            
            foreach (var product in db.Products) productList.Add(new SelectListItem{ Text = product.Name, Value = product.ProductId.ToString()});
            foreach (var order in db.Orders) orderList.Add(new SelectListItem{ Text = order.OrderId.ToString(), Value = order.OrderId.ToString()});
            foreach (var media in db.MediaTypes) mediaList.Add(new SelectListItem{ Text = media.Title, Value = media.MediaTypeId.ToString()});
            
            ViewData["productList"] = productList;
            ViewData["orderList"] = orderList;
            ViewData["mediaList"] = mediaList;
        }
    }
}

HappyDogShop2/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing.Printing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HappyDogShop2.Models;
using PagedList;

namespace HappyDogShop2.Controllers
{
    public class ProductsController : Controller
    {
        private MyDbContext db = new MyDbContext();

        
        
        // for users:
        
        public ActionResult UserIndex(int? page, int categoryId = -1 )
        {
            ViewData["categories"] = from category in db.Categories select category;
            ViewData["media"] = from media in db.MediaTypes select media;
            ViewData["saleList"] = from sale in db.Sales select sale;
            Console.WriteLine(categoryId);
            List<Product> list;
            if (categoryId == -2) //nowości
            {
                list = db.Products.OrderByDescending(product => product.ProductId).Take(10).ToList();
            }
            else if (categoryId == -3) //promocje
            {
                // list = ((db.Products.Where(product => product.SaleId != null).ToList()).Where(product => product.Sale.StartDate <= @DateTime.Now).ToList()).Where(product => product.Sale.EndDate >= @DateTime.Now).ToList();

                list = db.Products.Where(product => product.SaleId != null && product.Sale.StartDate <= @DateTime.Now &&
                                                    product.Sale.EndDate >= @DateTime.Now).ToList();

            }
            else if (categoryId != -1) 
            {
                list = db.Products.Where(product => product.CategoryId == categoryId).ToList();
                Console.WriteLine("poszla kategoria");
            }
            else //wszystko
            {
                list = db.Products.ToList();
            }
            int pageSize = 6;
            int pageNumber = (page ?? 1);
            return View(list.ToPagedList(pageNumber, pageSize));
        }

        // GET: Products/Details/5
        public ActionResult UserDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        
        // GET: Products
        public ActionResult AdminIndex(int categoryId = -1, string categoryName ="", string Name = "", int Price1 = -1, int Price2 = -1, bool Sale = false, bool inStock = true)
        {
            List<Product> list = db.Products.ToList();
            ViewBag.min = db.Products.Min(product => product.Price);
            ViewBag.max = db.Products.Max(product => product.Price);

            if (categoryId != -1) list = list.Where(product => product.CategoryId == categoryId).ToList();
            
            if (categoryName != "") list = list.Where(product => product.Category.Name == categoryName).ToList();

            if (Name != "") list = list.Where(product => product.Name == Name).ToList();
            
            if (Price1 != -1 & Price2 != -1) list = list.Where(product => product.Price >= Price1 && product.Price <= Price2).ToList();
            
            if (Sale == true) list = list.Where(product => product.Sale != null).ToList();
            
            if (inStock == false) list = list.Where(product => product.StockCount == 0).ToList();

            return View(list);
        }

        // GET: Products/Details/5
        public ActionResult AdminDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult AdminCreate()
        {
            prepareList();

            return View();
        }

        // POST: Products/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdminCreate([Bind(Include = "ProductId,Name,Description,Price,IsHidden,StockCount,MediaTypeId,CategoryId, SaleId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Products.Add(product);
                db.SaveChanges();
                return RedirectToAction("AdminIndex");
            }

            return View(product);
        }

        // GET: Products/Edit/5
        public ActionResult AdminEdit(int? id)
        {
            prepareList();
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AdminEdit([Bind(Include = "ProductId,Name,Description,Price,IsHidden,StockCount,MediaTypeId,CategoryId, SaleId")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AdminIndex");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult AdminDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("AdminIndex");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        public ActionResult _ProductLayout(string searchString = "")
        {
            List<Category> list = new List<Category>();
            if (searchString != "")
            {
                foreach (var category1 in db.Categories.Where(category => category.Name == searchString).ToList()) list.Add(category1);
                foreach (var category1 in db.Categories.Where(category => category.Parent.Name == searchString).ToList()) list.Add(category1);
            }
            else
            {
                list = db.Categories.ToList();
            }
            return View(list);
        }

        public void prepareList()
        {
            ViewData["categories"] = from category in db.Categories select category;
            ViewData["media"] = from media in db.MediaTypes select media;
            
            List<SelectListItem> categoryList = new List<SelectListItem>();
            List<SelectListItem> mediaList = new List<SelectListItem>();
            List<SelectListItem> saleList = new List<SelectListItem>();

            foreach (var category in db.Categories) categoryList.Add(new SelectListItem{ Text = category.Name, Value = category.CategoryId.ToString()});
            foreach (var sale in db.Sales) saleList.Add(new SelectListItem{ Text = sale.Name + ": " + sale.ValueInPercent + "%", Value = sale.SaleId.ToString()});
            foreach (var media in db.MediaTypes) mediaList.Add(new SelectListItem{ Text = media.Title, Value = media.MediaTypeId.ToString()});

            ViewData["categoriesList"] = categoryList;
            ViewData["mediaList"] = mediaList;
            ViewData["saleList"] = saleList;
        }
    }
}

HappyDogShop2/Views/Order/Create.cshtml
@model HappyDogShop2.Models.Order

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div style=" border-style: double; border-radius: 8px; border-color: #f7e6cf; padding: 30px; margin: 50px;" class="sawibox form-horizontal">
    <h4>Dodaj zamówienie</h4>
    <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AmountPaid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AmountPaid, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AmountPaid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Dodaj" class="btn btn-default" style=" margin-left: 215px; border-color: #e43e86 " />
        </div>
    </div>
    
    
</div>
}

<div>
    @Html.ActionLink("Wróć", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HappyDogShop2/Views/Order/Delete.cshtml
@model HappyDogShop2.Models.Order

@{
    ViewBag.Title = "Delete";
}

<h4>Czy jesteś pewien, że chcesz usunąć te zamówienie?</h4>
<div>
    <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountPaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountPaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" style="margin-left: 215px; border-color: #e43e86" /> |
            @Html.ActionLink("Wróć", "Index")
        </div>
    }
</div>

HappyDogShop2/Views/Order/Details.cshtml
@using HappyDogShop2.Controllers
@using HappyDogShop2.Models
@model HappyDogShop2.Models.Order

@{
    ViewBag.Title = "Details";
}



<div>
    <h4>Szczegóły:</h4>
    <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AmountPaid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AmountPaid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
            <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
    <h4>Produkty:</h4>
    <table style="width: 70%; margin: 0 auto" class="table">
            <tr>
                <th>
                    @Html.DisplayName("ilosc")
                </th>
                <th>
                    @Html.DisplayName("Nazwa produktu")
                </th>
                <th>
                    @Html.DisplayName("Cena produktu")
                </th>

            </tr>
        @foreach (var item in (IEnumerable<CartItem>) ViewData["cartItems"]){
       
        <tr>
                    <td style="width: 100px">
                        @item.Quantity
                    </td>
   
                            <td style="width: 200px">
                                @item.Product.Name
                            </td>
                            <td style="width: 100px">
                                @item.Product.Price.ToString()
                            </td>
                            <td style="width: 100px">
                                @foreach (var media in (IEnumerable<MediaType>) ViewData["media"])
                                 { 
                                     if (@item.Product.MediaTypeId == media.MediaTypeId) 
                                    { 
                                         <img style="height: 50px" src="@media.ImagePath"/> 
                                    } 
                                 } 
    
                            </td>
                       
                    <td>
                        @Html.ActionLink("Szczegóły", "UserDetails", "Products",new {id = item.ProductId}, new {} ) 
                    </td>
                </tr>
    
            }
            <tr>
                <td>
    
                </td>
                <td style="padding-left: 150px">
                    @* Suma: *@
                </td>
                <td >
                    @* @ViewBag.sum *@
                </td>
                <td colspan="2" style="padding-left: 110px">
                    @* <button class="btn btn-default" style=" border-color: #e43e86">@Html.ActionLink("Złóż zamówienie", "PlaceAnOrder", "Order", new *@
                    @*                                                                    {OrderId = @Session["orderId"], AmountPaid = @ViewBag.sum }, new {})</button> *@
                    @* *@
    
                </td>
            </tr>
    </table>


</div> 

<p>

</p>

HappyDogShop2/Views/Order/Edit.cshtml
@model HappyDogShop2.Models.Order

@{
    ViewBag.Title = "Edit";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div style=" border-style: double; border-radius: 8px; border-color: #f7e6cf; padding: 30px; margin: 50px;" class="sawibox form-horizontal">
        <h4>Edytuj zamówienie:</h4>
        <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.AmountPaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AmountPaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AmountPaid, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="wybrany" >
                    <option value="@(Model.Status == HappyDogShop2.Models.Status.Otwarte)">Otwarte </option>
                    <option value="@(Model.Status == HappyDogShop2.Models.Status.Przyjęte)">Przyjęte</option>
                    <option value="@(Model.Status == HappyDogShop2.Models.Status.Zapłacone)">Zapłacone</option>
                    <option value="@(Model.Status == HappyDogShop2.Models.Status.Wysłane)">Wysłane</option>
                    <option value="@(Model.Status == HappyDogShop2.Models.Status.Dostarczone)">Dostarczone</option>
                    </select>
                @* @Html.EditorFor(model => model.Status, new {htmlAttributes = new {@class = "form-control"}}) *@
                @Html.ValidationMessageFor(model => model.Status, "", new {@class = "text-danger"})
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" style="margin-left: 215px; border-color: #e43e86"/>
            </div>
        </div>
        
    </div>
}

<div>
    @Html.ActionLink("Wróć", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HappyDogShop2/Views/Order/Index.cshtml
@model IEnumerable<HappyDogShop2.Models.Order>

@{
    ViewBag.Title = "Index";
}

<h4>Zamówienia:</h4>

<p>
    @Html.ActionLink("Utwórz nowe", "Create")
</p>

<form asp-controller="Orders" asp-action="Index" method="get">
    <p>
        Wyszukaj użytkownika: <input type="text" name="UserId"/>
        <input type="submit" value="Szukaj"/>
    </p>
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AmountPaid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AmountPaid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.OrderId }) |
            @Html.ActionLink("Szczegóły", "Details", new { id=item.OrderId }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.OrderId })
        </td>
    </tr>
}

</table>

HappyDogShop2/Views/Order/UserIndex.cshtml
@using System.Collections
@using HappyDogShop2.Models
@model IEnumerable<HappyDogShop2.Models.Order>

@{
    ViewBag.Title = "Index";
}

<h4 style="width: 70%; margin: 45px auto">Twoje zamówienia: </h4>

@* <p> *@
@*     Mozna dac tez liczbe produktow zy cos a dopiero w szczegolach ich liste *@
@* </p> *@

<div class="sawibox">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AmountPaid) 
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
    
            <th></th>
        </tr>
    
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.AmountPaid) zł
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @* @Html.DisplayFor(modelItem => item.CartItems.Count) *@
                    
                    @* @Html.Display(item.CartItems.Count.ToString()) *@
                    @* @item.CartItems.Count *@
                    @((IEnumerable<CartItem>) ViewData[item.OrderId.ToString()])
                   
                </td>
                <td>
                    @Html.ActionLink("Szczegóły", "Details", new { id=item.OrderId }) |
                    @Html.ActionLink("Zamów ponownie", "OrderAgain", new { OldOrderId=item.OrderId, NewOrderId = Session["orderId"] }) |
                    
                </td>
            </tr>
        }
    
    </table>
</div>