HappyDogShop2/Models/CartItem.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HappyDogShop2.Models
{
    public class CartItem
    {
        [Key]
        public int ItemId { get; set; }  
        [Required(ErrorMessage = "Wybierz między 1 a 15"), Display(Name = "Ilość"), Range(1, 15)]
        public int Quantity  { get; set; }
        
        [ForeignKey("Product"), Display(Name = "Produkt")]
        public int ProductId { get; set; }
        public virtual Product Product { get; set; }
        
        [ForeignKey("Order"), Display(Name = "Zamówienie")]
        public int OrderId { get; set; }
        public virtual Order Order { get; set; }
        
    }
}

HappyDogShop2/Controllers/CartItemController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using HappyDogShop2.Models;

namespace HappyDogShop2.Controllers
{
    public class CartItemController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: CartItems
        public ActionResult Index(int OrderId = -1)
        {
            List<CartItem> list= new List<CartItem>();
            if (OrderId != -1)
            {
                list = db.CartItems.Where(cartItem => cartItem.OrderId == OrderId).ToList();
            }
            else
            {
                list = db.CartItems.ToList();
            }
            return View(list);
        }

        // GET: CartItems/Details/5
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // GET: CartItems/Create
        public ActionResult Create()
        {
            prepareList();
            return View();
        }

        // POST: CartItems/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemId,Quantity,ProductId, OrderId")] CartItem cartItem)
        {
            //TODO jak zrobic to zeby przy braku otwartego zamowienia tworzylo nowe
            // if (cartItem.OrderId = null)
            // {
            //     Order order = new Order();
            //     Session["orderId"] = order.OrderId;
            // }
            if (ModelState.IsValid)
            {
                db.CartItems.Add(cartItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cartItem);
        }
        public ActionResult Create2(int Quantity, int ProductId, int? OrderId)
        {
            Console.Write(OrderId);
            if (OrderId == null)
            {
                if (Session["userId"] == null)
                {
                    return RedirectToAction("Index", "Login");
                }
                else
                {
                    Order order = new Order();
                    order.UserId = (int) Session["userId"];
                    order.Date = DateTime.Now;
                    db.Orders.Add(order);
                    db.SaveChanges();                    
                    Session["orderId"] = order.OrderId;
                }
            }

            CartItem cartItem = new CartItem();
            cartItem.Quantity = Quantity;
            cartItem.ProductId = ProductId;
            cartItem.OrderId = (int) Session["orderId"];
            db.CartItems.Add(cartItem);
            db.SaveChanges();
            return RedirectToAction("UserIndex", new { OrderId=cartItem.OrderId} );

        }

        // GET: CartItems/Edit/5
        public ActionResult Edit(int? id)
        {
            prepareList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemId,Quantity,ProductId, OrderId")] CartItem cartItem)
        {
            db.Entry(cartItem).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("UserIndex");
            if (ModelState.IsValid)
            {
                db.Entry(cartItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("UserIndex");
            }
            return View(cartItem);
        }

        // GET: CartItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }

        // POST: CartItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartItem cartItem = db.CartItems.Find(id);
            db.CartItems.Remove(cartItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult UserIndex(int? OrderId = 0)
        {
            ViewData["categories"] = from category in db.Categories select category;
            ViewData["media"] = from media in db.MediaTypes select media;
            ViewData["products"] = from product in db.Products select product;
            ViewBag.orderId = OrderId;
            float sum = 0;
            
            List<CartItem> list= new List<CartItem>();
            
            if (OrderId > 0)
            {
                list = db.CartItems.Where(cartItem => cartItem.OrderId == OrderId).ToList();
            }
            foreach (CartItem item in list)
            {
                Product product = db.Products.Find(item.ProductId);
                sum += product.Price * item.Quantity;
            }

            ViewBag.sum = sum;
            return View(list);
        }
        public void prepareList()
        {
            List<SelectListItem> productList = new List<SelectListItem>();
            List<SelectListItem> orderList = new List<SelectListItem>();

            foreach (var product in db.Products) productList.Add(new SelectListItem{ Text = product.Name, Value = product.ProductId.ToString()});
            foreach (var order in db.Orders) orderList.Add(new SelectListItem{ Text = order.OrderId.ToString(), Value = order.OrderId.ToString()});

            ViewData["productList"] = productList;
            ViewData["orderList"] = orderList;
        }
    }
}

HappyDogShop2/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using HappyDogShop2.Models;

namespace HappyDogShop2.Controllers
{
    public class OrderController : Controller
    {
       private MyDbContext db = new MyDbContext();

        // GET: Orders
        public ActionResult Index(int UserId = -1)
        {
            List<Order> list= new List<Order>();
            if (UserId != -1)
            {
                list = db.Orders.Where(order => order.UserId == UserId).ToList();
            }
            else
            {
                list = db.Orders.ToList();
            }
            return View(list);
        }
        
        public ActionResult UserIndex(int UserId)
        {
            List<Order> list= new List<Order>();
            list = db.Orders.Where(order => order.UserId == UserId).ToList();
            foreach (var order in list)
            {
                ViewData[order.OrderId.ToString()] = order.CartItems;
            }

            ViewBag.count = 0;
            return View(list);
        }

        // GET: Orders/Details/5
        public ActionResult Details(int? id)
        {
            prepareList();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewData["cartItems"] = db.CartItems.Where(item => item.Order.OrderId == order.OrderId).ToList();
            return View(order);
        }

        // GET: Orders/Create
        public ActionResult Create()
        {
        
            return View();
        }

        // POST: Orders/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrderId,UserId,AmountPaid, Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            Session["orderId"] = order.OrderId;
            return View(order);
        }
        
        // GET: Orders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OrderId,UserId,AmountPaid, Status")] Order order)
        {
            if (ModelState.IsValid)
            {
                if (Status.Otwarte.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Otwarte;
                if (Status.Zapłacone.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Zapłacone;
                if (Status.Dostarczone.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Dostarczone;
                if (Status.Przyjęte.ToString().Equals(Request.Form["wybrany"]))  order.Status = Status.Przyjęte;
                if (Status.Wysłane.ToString().Equals(Request.Form["wybrany"])) order.Status = Status.Wysłane;
                
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult OrderAgain(int? NewOrderId, int OldOrderId)
        {
            if (NewOrderId == null)
            {
                Order order = new Order();
                Console.Write((int) Session["userId"]);
                    order.UserId = (int) Session["userId"];
                    order.Date = DateTime.Now;
                    db.Orders.Add(order);
                    db.SaveChanges();                    
                    Session["orderId"] = order.OrderId;
                
            }

            foreach (var item in db.CartItems.Where(i=>i.OrderId == OldOrderId))
            {
                CartItem cartItem = new CartItem();
                cartItem.Quantity = item.Quantity;
                cartItem.ProductId = item.ProductId;
                cartItem.OrderId = (int) Session["orderId"];
                db.CartItems.Add(cartItem);
            }
            
            db.SaveChanges();
            return RedirectToAction("UserIndex", "CartItem", new { OrderId=(int) Session["orderId"]} );
        }
        
        public ActionResult PlaceAnOrder(int OrderId, decimal AmountPaid)
        {
            Order order = db.Orders.Find(OrderId);
            Console.Write(order.UserId);
            order.AmountPaid = AmountPaid;
            order.Status = Status.Przyjęte;

            List<CartItem> itemList = new List<CartItem>();
            itemList = db.CartItems.Where(item => item.Order.OrderId == order.OrderId).ToList();
            foreach (var item in itemList) db.Products.Where(product => product.ProductId == item.ProductId).ToList().ForEach(pr => pr.StockCount = pr.StockCount - item.Quantity);
            
            db.Entry(order).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("UserIndex", new {UserId = order.UserId});
        }
        public void prepareList()
        {
            ViewData["media"] = from media in db.MediaTypes select media;
            List<SelectListItem> productList = new List<SelectListItem>();
            List<SelectListItem> orderList = new List<SelectListItem>();
            List<SelectListItem> mediaList = new List<SelectListItem>();
            
            foreach (var product in db.Products) productList.Add(new SelectListItem{ Text = product.Name, Value = product.ProductId.ToString()});
            foreach (var order in db.Orders) orderList.Add(new SelectListItem{ Text = order.OrderId.ToString(), Value = order.OrderId.ToString()});
            foreach (var media in db.MediaTypes) mediaList.Add(new SelectListItem{ Text = media.Title, Value = media.MediaTypeId.ToString()});
            
            ViewData["productList"] = productList;
            ViewData["orderList"] = orderList;
            ViewData["mediaList"] = mediaList;
        }
    }
}

HappyDogShop2/Controllers/TrashController.cs
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using HappyDogShop2.Models;

namespace HappyDogShop2.Controllers
{
    private MyDbContext db = new MyDbContext();
    public class TrashController : Controller
    {
        // GET
        public ActionResult Index()
        {
            List<CartItem> list= new List<CartItem>();
            return View(list);

        }
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CartItem cartItem = db.CartItems.Find(id);
            if (cartItem == null)
            {
                return HttpNotFound();
            }
            return View(cartItem);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CartItem cartItem = db.CartItems.Find(id);
            db.CartItems.Remove(cartItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

HappyDogShop2/Views/CartItem/Create.cshtml
@model HappyDogShop2.Models.CartItem

@{
    ViewBag.Title = "Create";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div style=" border-style: double; border-radius: 8px; border-color: #f7e6cf; padding: 30px; margin: 50px;" class="sawibox form-horizontal">
    <h4>Dodaj produkt do koszyka</h4>
    <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.ProductId, ViewData["productList"] as List<SelectListItem>, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.OrderId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.OrderId, ViewData["orderList"] as List<SelectListItem>, new {htmlAttributes = new {@class = "form-control"}})
            @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Dodaj" class="btn btn-default" style=" margin-left: 215px; border-color: #e43e86 " />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Wróć", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HappyDogShop2/Views/CartItem/Delete.cshtml
@model HappyDogShop2.Models.CartItem

@{
    ViewBag.Title = "Delete";
}

<h4>Czy jesteś pewien, że chcesz usunąć ten produkt z koszyka?</h4>
<div>
    <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń" class="btn btn-default" style="margin-left: 215px; border-color: #e43e86" /> |
            @Html.ActionLink("Wróć", "Index")
        </div>
    }
</div>

HappyDogShop2/Views/CartItem/Details.cshtml
@model HappyDogShop2.Models.CartItem

@{
    ViewBag.Title = "Details";
}



<div>
    <h4>Szczegóły:</h4>
    <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edytuj", "Edit", new { id = Model.ItemId}) |
    @Html.ActionLink("Wróć", "Index")
</p>

HappyDogShop2/Views/CartItem/Edit.cshtml
@model HappyDogShop2.Models.CartItem

@{
    ViewBag.Title = "Edit";
}




@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div style=" border-style: double; border-radius: 8px; border-color: #f7e6cf; padding: 30px; margin: 50px;" class="sawibox form-horizontal">
        <h4>Edytuj promocję:</h4>
        <hr style="height: 1px; background-color: #e43e86; color: #e43e86" />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderId)

        <div class="form-group">
                @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                </div>
            </div>
        
            <div class="form-group">
                @Html.LabelFor(model => model.ProductId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.ProductId, ViewData["productList"] as List<SelectListItem>, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.ProductId, "", new { @class = "text-danger" })
                </div>
            </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.OrderId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.OrderId, ViewData["orderList"] as List<SelectListItem>, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" style="margin-left: 215px; border-color: #e43e86"/>
            </div>
        </div>
        
    </div>
}

<div>
    @Html.ActionLink("Wróć", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HappyDogShop2/Views/CartItem/Index.cshtml
@model IEnumerable<HappyDogShop2.Models.CartItem>

@{
    ViewBag.Title = "Index";
}

<h4>Produkty koszykowe:</h4>

<p>
    @Html.ActionLink("Utwórz nowe", "Create")
</p>

<form asp-controller="CartItem" asp-action="Index" method="get">
    <p>
        Wyszukaj zamówienie: <input type="text" name="OrderId"/>
        <input type="submit" value="Szukaj"/>
    </p>
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderId)
        </td>
        <td>
            @Html.ActionLink("Edytuj", "Edit", new { id=item.ItemId }) |
            @Html.ActionLink("Szczegóły", "Details", new { id=item.ItemId }) |
            @Html.ActionLink("Usuń", "Delete", new { id=item.ItemId })
        </td>
    </tr>
}

</table>

HappyDogShop2/Views/CartItem/UserIndex.cshtml
@using HappyDogShop2.Models
@model IEnumerable<HappyDogShop2.Models.CartItem>
@{
    ViewBag.Title = "CartUserIndex";
}

<h4 style="width: 70%; margin: 45px auto">Twoje zamówienie: @Session["OrderId"]</h4>

<div class="sawibox">
    <table style="width: 100%; margin: 0 auto" class="table">
        <tr>
            <th style="width: 100px">
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayName("Nazwa produktu")
            </th>
            <th>
                @Html.DisplayName("Cena produktu")
            </th>
            @* <th> *@
            @*     @Html.DisplayName("Media") *@
            @* </th> *@
    
        </tr>
    
        @foreach (var item in Model)
        {
            <tr>
                <td style="width: 100px">
                    @Html.EditorFor(modelItem => item.Quantity, new {htmlAttributes = new {@class = "form-control"}})
                </td>
                @foreach (Product product in (IEnumerable<Product>) ViewData["products"])
                {
                    if (item.ProductId == product.ProductId)
                    {
                        <td style="width: 200px">
                            @product.Name
                        </td>
                        <td style="width: 100px">
                            @product.Price.ToString()
                        </td>
                        <td style="width: 100px">
                            @foreach (var media in (IEnumerable<MediaType>) ViewData["media"])
                            {
                                if (@product.MediaTypeId == media.MediaTypeId)
                                {
                                    <img style="height: 50px" src="@media.ImagePath"/>
                                }
                            }
    
                        </td>
                    }
    
                }
                <td>
                    @* @Html.ActionLink("Edytuj", "Edit", new { id=item.ItemId }) | *@
                    @Html.ActionLink("Szczegóły", "Details", new {id = item.ItemId})
                    @*@Html.ActionLink("Usuń", "Index", "Trash", new {id = item.ItemId}, new {})*@
                </td>
                <td>
                    <button class="btn btn-default" style=" border-color: #e43e86">
    
                        @Html.ActionLink("Zapisz zmiany", "Edit", "CartItem", new
                        {ItemId = item.ItemId, Quantity = @item.Quantity, ProductId = item.ProductId, OrderId = @Session["orderId"]}, new {})
                    </button>            
                    @* //to nie dziala *@
                </td>
    
            </tr>
    
        }
        <tr>
            <td>
    
            </td>
            <td style="padding-left: 150px">
                Suma:
            </td>
            <td >
                @ViewBag.sum
            </td>
            <td colspan="2" style="padding-left: 110px">
    
                
                
                <button class="btn btn-default" style=" border-color: #e43e86">@Html.ActionLink("Złóż zamówienie", "PlaceAnOrder", "Order", new
                                                                               {OrderId = @Session["orderId"], AmountPaid = @ViewBag.sum}, new {})</button>
    
    
            </td>
        </tr>
    </table>
</div>
<div>
    @Html.ActionLink("Wróć", "UserIndex", "Products")
</div>